{{- if and .Values.ingressRoute.enabled (.Capabilities.APIVersions.Has "traefik.io/v1alpha1") -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "v-rising.fullname" . }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
spec:
  {{- with .Values.ingressRoute.entryPointNames.game }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
  - services:
    - name: {{ include "v-rising.fullname" . }}
      port: game
      nativeLB: {{ .Values.ingressRoute.nativeLB }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ include "v-rising.fullname" . }}-query
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
spec:
  {{- with .Values.ingressRoute.entryPointNames.query }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
  - services:
    - name: {{ include "v-rising.fullname" . }}
      port: query
      nativeLB: {{ .Values.ingressRoute.nativeLB }}
{{- end }}