apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "v-rising.fullname" . }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
data:
  VR_GAME_PORT: {{ .Values.service.gamePort | quote }}
  VR_QUERY_PORT: {{ .Values.service.queryPort | quote }}
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}