apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "v-rising.fullname" . }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "v-rising.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "v-rising.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "v-rising.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "v-rising.fullname" . }}
            - secretRef:
                name: {{ include "v-rising.fullname" . }}
          ports:
            - name: game
              containerPort: {{ .Values.service.gamePort }}
              protocol: UDP
            - name: query
              containerPort: {{ .Values.service.queryPort }}
              protocol: UDP
          livenessProbe:
            exec:
              command:
                - sh
                - /home/steam/healthz.sh
            initialDelaySeconds: 600
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - /home/steam/healthz.sh
            initialDelaySeconds: 600
            periodSeconds: 10
          volumeMounts:
            - mountPath: /vrising/server
              name: v-server
            - mountPath: /vrising/data/Saves/v3/{{ .Values.config.VR_SAVE_NAME }}
              name: v-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: v-server
          emptyDir: {}
        - name: v-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "v-rising.fullname" . }}
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
