{{- if and (.Values.persistence.data).enabled (not .Values.persistence.data.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "v-rising.fullname" . }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
spec:
 storageClassName: {{ .Values.persistence.data.storageClass }}
 accessModes:
   - {{ .Values.persistence.data.accessMode | quote }}
 resources:
   requests:
     storage: {{ .Values.persistence.data.size | quote }}
{{- end }}