apiVersion: v1
kind: Service
metadata:
  name: {{ include "v-rising.fullname" . }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.gamePort }}
      targetPort: game
      protocol: UDP
      name: game
    - port: {{ .Values.service.queryPort }}
      targetPort: query
      protocol: UDP
      name: query
  selector:
    {{- include "v-rising.selectorLabels" . | nindent 4 }}
